-- Main defect rule seed
INSERT INTO defect_workflow_rules (defect_type, default_problem_level, recommended_priority) VALUES
('Wrong Expiry Date Printing','Can Be Corrected','medium'),
('Untidy Label','Can Be Corrected','low'),
('Wrong Label Used','Hold for Review','medium'),
('Label Not Set Properly','Can Be Corrected','low'),
('Leaking Packaging','Food Safety Risk','high'),
('Loose Sealing','Food Safety Risk','high'),
('Bloated Packaging','Food Safety Risk','critical'),
('Smell Change','Food Safety Risk','critical'),
('Taste Change','Food Safety Risk','critical'),
('Product Spoiled','Food Safety Risk','critical'),
('Foreign Matter','Food Safety Risk','critical'),
('Weight Issue','Hold for Review','medium'),
('Packaging Material Damaged','Hold for Review','medium'),
('Retort Process Issue','Food Safety Risk','critical'),
('Colour / Texture Change','Hold for Review','high'),
('Ingredient Quality Issue','Hold for Review','medium'),
('Wrong Batch Code on Label','Hold for Review','medium'),
('Other','Hold for Review','medium')
ON CONFLICT (defect_type) DO UPDATE SET
  default_problem_level = EXCLUDED.default_problem_level,
  recommended_priority = EXCLUDED.recommended_priority,
  updated_at = CURRENT_TIMESTAMP;

-- Keep existing defect_types aligned too
INSERT INTO defect_types (defect_type_name, defect_category, default_problem_level)
SELECT defect_type, 'Quality Defect', default_problem_level FROM defect_workflow_rules
ON CONFLICT (defect_type_name) DO UPDATE SET default_problem_level = EXCLUDED.default_problem_level;

-- Stage mappings
INSERT INTO defect_type_mappings (detected_at_stage, defect_type_id)
SELECT stage, dt.id
FROM (
  VALUES
  ('Ingredient Preparation','Foreign Matter'),('Ingredient Preparation','Smell Change'),('Ingredient Preparation','Taste Change'),('Ingredient Preparation','Ingredient Quality Issue'),('Ingredient Preparation','Other'),
  ('Cooking','Smell Change'),('Cooking','Taste Change'),('Cooking','Product Spoiled'),('Cooking','Foreign Matter'),('Cooking','Colour / Texture Change'),('Cooking','Other'),
  ('Packing / Filling','Foreign Matter'),('Packing / Filling','Weight Issue'),('Packing / Filling','Packaging Material Damaged'),('Packing / Filling','Loose Sealing'),('Packing / Filling','Other'),
  ('Sealing','Loose Sealing'),('Sealing','Leaking Packaging'),('Sealing','Other'),
  ('Retort Process','Bloated Packaging'),('Retort Process','Product Spoiled'),('Retort Process','Smell Change'),('Retort Process','Taste Change'),('Retort Process','Retort Process Issue'),('Retort Process','Colour / Texture Change'),('Retort Process','Other'),
  ('Labelling / Expiry Printing','Wrong Expiry Date Printing'),('Labelling / Expiry Printing','Untidy Label'),('Labelling / Expiry Printing','Wrong Label Used'),('Labelling / Expiry Printing','Label Not Set Properly'),('Labelling / Expiry Printing','Wrong Batch Code on Label'),('Labelling / Expiry Printing','Other'),
  ('Stock Storage','Bloated Packaging'),('Stock Storage','Leaking Packaging'),('Stock Storage','Smell Change'),('Stock Storage','Taste Change'),('Stock Storage','Product Spoiled'),('Stock Storage','Packaging Material Damaged'),('Stock Storage','Other'),
  ('Before Delivery','Wrong Expiry Date Printing'),('Before Delivery','Untidy Label'),('Before Delivery','Wrong Label Used'),('Before Delivery','Label Not Set Properly'),('Before Delivery','Wrong Batch Code on Label'),('Before Delivery','Leaking Packaging'),('Before Delivery','Bloated Packaging'),('Before Delivery','Smell Change'),('Before Delivery','Packaging Material Damaged'),('Before Delivery','Other'),
  ('After Customer Receives Product','Leaking Packaging'),('After Customer Receives Product','Bloated Packaging'),('After Customer Receives Product','Smell Change'),('After Customer Receives Product','Taste Change'),('After Customer Receives Product','Product Spoiled'),('After Customer Receives Product','Wrong Expiry Date Printing'),('After Customer Receives Product','Wrong Label Used'),('After Customer Receives Product','Wrong Batch Code on Label'),('After Customer Receives Product','Other')
) AS m(stage, defect_type)
JOIN defect_types dt ON dt.defect_type_name = m.defect_type
ON CONFLICT (detected_at_stage, defect_type_id) DO NOTHING;

-- Option seeds
DELETE FROM defect_workflow_options;
INSERT INTO defect_workflow_options (defect_type, option_type, option_value, sort_order) VALUES
('Wrong Expiry Date Printing','product_handling','Relabel Required',1),
('Wrong Expiry Date Printing','product_handling','Release After Check',2),
('Wrong Expiry Date Printing','product_handling','To Be Decided After Inspection',3),
('Wrong Expiry Date Printing','product_handling','Discard Required',4),
('Wrong Expiry Date Printing','machine_check','Check expiry date mould',1),
('Wrong Expiry Date Printing','machine_check','Check date stamp / printer setting',2),
('Wrong Expiry Date Printing','machine_check','Verify expiry date before labelling',3),
('Wrong Expiry Date Printing','machine_check','Update expiry checking checklist',4),
('Wrong Expiry Date Printing','related_tool','Expiry Date Mould',1),
('Wrong Expiry Date Printing','related_tool','Date Stamp Printer',2),
('Wrong Expiry Date Printing','related_tool','Label Printer',3),
('Wrong Expiry Date Printing','related_tool','Expiry Checking Checklist',4),
('Wrong Expiry Date Printing','related_tool','Labelling Area',5),
('Wrong Expiry Date Printing','root_cause','Wrong expiry date mould used',1),
('Wrong Expiry Date Printing','root_cause','Date stamp / printer setting incorrect',2),
('Wrong Expiry Date Printing','root_cause','Wrong batch expiry reference used',3),
('Wrong Expiry Date Printing','root_cause','Expiry verification not performed',4),
('Wrong Expiry Date Printing','root_cause','Expiry checking checklist not followed',5),
('Wrong Expiry Date Printing','root_cause','Other',6),
('Untidy Label','product_handling','Relabel Required',1),
('Untidy Label','product_handling','Release After Check',2),
('Untidy Label','product_handling','To Be Decided After Inspection',3),
('Untidy Label','machine_check','Check label placement method',1),
('Untidy Label','machine_check','Check label material / adhesive',2),
('Untidy Label','machine_check','Review labelling process',3),
('Untidy Label','machine_check','Review worker handling process if needed',4),
('Untidy Label','related_tool','Label Printer',1),
('Untidy Label','related_tool','Label Sticker',2),
('Untidy Label','related_tool','Label Cutter',3),
('Untidy Label','related_tool','Labelling Table',4),
('Untidy Label','related_tool','Labelling Area',5),
('Untidy Label','root_cause','Label applied unevenly',1),
('Untidy Label','root_cause','Label position not checked',2),
('Untidy Label','root_cause','Rushed labelling process',3),
('Untidy Label','root_cause','Label adhesive issue',4),
('Untidy Label','root_cause','Label paper quality issue',5),
('Untidy Label','root_cause','Label printer alignment issue',6),
('Untidy Label','root_cause','Other',7),
('Wrong Label Used','product_handling','Relabel Required',1),
('Wrong Label Used','product_handling','Hold for Review',2),
('Wrong Label Used','product_handling','To Be Decided After Inspection',3),
('Wrong Label Used','product_handling','Discard Required',4),
('Wrong Label Used','machine_check','Check label storage / label selection process',1),
('Wrong Label Used','machine_check','Verify product-label matching before labelling',2),
('Wrong Label Used','machine_check','Update label checking checklist',3),
('Wrong Label Used','machine_check','Review worker handling process if needed',4),
('Wrong Label Used','related_tool','Product Label',1),
('Wrong Label Used','related_tool','Label Storage Box',2),
('Wrong Label Used','related_tool','Label Checking Checklist',3),
('Wrong Label Used','related_tool','Labelling Area',4),
('Wrong Label Used','root_cause','Wrong label selected',1),
('Wrong Label Used','root_cause','Product-label matching not verified',2),
('Wrong Label Used','root_cause','Label checking checklist not followed',3),
('Wrong Label Used','root_cause','Labels stored too closely',4),
('Wrong Label Used','root_cause','Old and new labels mixed',5),
('Wrong Label Used','root_cause','Other',6),
('Label Not Set Properly','product_handling','Relabel Required',1),
('Label Not Set Properly','product_handling','Release After Check',2),
('Label Not Set Properly','product_handling','To Be Decided After Inspection',3),
('Label Not Set Properly','machine_check','Check label placement method',1),
('Label Not Set Properly','machine_check','Check label material / adhesive',2),
('Label Not Set Properly','machine_check','Review labelling SOP',3),
('Label Not Set Properly','machine_check','Review worker handling process if needed',4),
('Label Not Set Properly','related_tool','Label Sticker',1),
('Label Not Set Properly','related_tool','Label Printer',2),
('Label Not Set Properly','related_tool','Label Cutter',3),
('Label Not Set Properly','related_tool','Packaging Surface',4),
('Label Not Set Properly','related_tool','Labelling Table',5),
('Label Not Set Properly','root_cause','Label applied incorrectly',1),
('Label Not Set Properly','root_cause','Label adhesive weak',2),
('Label Not Set Properly','root_cause','Packaging surface oily/wet',3),
('Label Not Set Properly','root_cause','Label size not suitable',4),
('Label Not Set Properly','root_cause','Worker handling method issue',5),
('Label Not Set Properly','root_cause','Other',6),
('Leaking Packaging','product_handling','Discard Required',1),
('Leaking Packaging','product_handling','Repack Required',2),
('Leaking Packaging','product_handling','Hold for Investigation',3),
('Leaking Packaging','product_handling','To Be Decided After Inspection',4),
('Leaking Packaging','machine_check','Inspect sealing machine temperature',1),
('Leaking Packaging','machine_check','Inspect sealing pressure',2),
('Leaking Packaging','machine_check','Check pouch material quality',3),
('Leaking Packaging','machine_check','Review sealing SOP',4),
('Leaking Packaging','related_tool','Sealing Machine',1),
('Leaking Packaging','related_tool','Sealing Bar',2),
('Leaking Packaging','related_tool','Retort Pouch',3),
('Leaking Packaging','related_tool','Packaging Material',4),
('Leaking Packaging','related_tool','Sealing Area',5),
('Leaking Packaging','root_cause','Sealing temperature too low',1),
('Leaking Packaging','root_cause','Sealing pressure not enough',2),
('Leaking Packaging','root_cause','Sealing time too short',3),
('Leaking Packaging','root_cause','Pouch not placed correctly',4),
('Leaking Packaging','root_cause','Seal area contaminated before sealing',5),
('Leaking Packaging','root_cause','Pouch material defect',6),
('Leaking Packaging','root_cause','Other',7),
('Loose Sealing','product_handling','Discard Required',1),
('Loose Sealing','product_handling','Repack Required',2),
('Loose Sealing','product_handling','Hold for Investigation',3),
('Loose Sealing','product_handling','To Be Decided After Inspection',4),
('Loose Sealing','machine_check','Inspect sealing machine temperature',1),
('Loose Sealing','machine_check','Inspect sealing pressure',2),
('Loose Sealing','machine_check','Check sealing machine condition',3),
('Loose Sealing','machine_check','Review sealing SOP',4),
('Loose Sealing','related_tool','Sealing Machine',1),
('Loose Sealing','related_tool','Sealing Bar',2),
('Loose Sealing','related_tool','Retort Pouch',3),
('Loose Sealing','related_tool','Sealing Area',4),
('Loose Sealing','root_cause','Sealing temperature incorrect',1),
('Loose Sealing','root_cause','Sealing pressure incorrect',2),
('Loose Sealing','root_cause','Sealing time too short',3),
('Loose Sealing','root_cause','Pouch not aligned properly',4),
('Loose Sealing','root_cause','Seal area not clean',5),
('Loose Sealing','root_cause','Pouch thickness issue',6),
('Loose Sealing','root_cause','Other',7),
('Bloated Packaging','product_handling','Discard Required',1),
('Bloated Packaging','product_handling','Hold for Investigation',2),
('Bloated Packaging','product_handling','To Be Decided After Inspection',3),
('Bloated Packaging','machine_check','Review retort process',1),
('Bloated Packaging','machine_check','Check retort temperature / pressure',2),
('Bloated Packaging','machine_check','Check cooling process',3),
('Bloated Packaging','machine_check','Check storage condition',4),
('Bloated Packaging','machine_check','Investigate possible spoilage source',5),
('Bloated Packaging','related_tool','Retort Machine',1),
('Bloated Packaging','related_tool','Retort Temperature Record',2),
('Bloated Packaging','related_tool','Retort Pressure Record',3),
('Bloated Packaging','related_tool','Cooling Area',4),
('Bloated Packaging','related_tool','Storage Area',5),
('Bloated Packaging','related_tool','Thermometer',6),
('Bloated Packaging','root_cause','Retort temperature not reached',1),
('Bloated Packaging','root_cause','Retort time insufficient',2),
('Bloated Packaging','root_cause','Retort pressure issue',3),
('Bloated Packaging','root_cause','Product spoilage',4),
('Bloated Packaging','root_cause','Storage temperature issue',5),
('Bloated Packaging','root_cause','Cooling process issue',6),
('Bloated Packaging','root_cause','Other',7),
('Smell Change','product_handling','Discard Required',1),
('Smell Change','product_handling','Hold for Investigation',2),
('Smell Change','product_handling','To Be Decided After Inspection',3),
('Smell Change','machine_check','Review cooking process',1),
('Smell Change','machine_check','Check ingredient freshness',2),
('Smell Change','machine_check','Check retort process',3),
('Smell Change','machine_check','Check storage condition',4),
('Smell Change','related_tool','Cooking Equipment',1),
('Smell Change','related_tool','Ingredient Record',2),
('Smell Change','related_tool','Cooking Record',3),
('Smell Change','related_tool','Retort Machine',4),
('Smell Change','related_tool','Storage Area',5),
('Smell Change','root_cause','Ingredient freshness issue',1),
('Smell Change','root_cause','Product spoilage',2),
('Smell Change','root_cause','Retort process insufficient',3),
('Smell Change','root_cause','Storage temperature issue',4),
('Smell Change','root_cause','Product stored too long',5),
('Smell Change','root_cause','Contamination during cooking/packing',6),
('Smell Change','root_cause','Other',7),
('Taste Change','product_handling','Discard Required',1),
('Taste Change','product_handling','Hold for Investigation',2),
('Taste Change','product_handling','To Be Decided After Inspection',3),
('Taste Change','machine_check','Review recipe / cooking process',1),
('Taste Change','machine_check','Check ingredient quality',2),
('Taste Change','machine_check','Check retort process',3),
('Taste Change','machine_check','Check storage condition',4),
('Taste Change','related_tool','Cooking Equipment',1),
('Taste Change','related_tool','Recipe Checklist',2),
('Taste Change','related_tool','Ingredient Record',3),
('Taste Change','related_tool','Retort Machine',4),
('Taste Change','related_tool','Storage Area',5),
('Taste Change','root_cause','Ingredient quality issue',1),
('Taste Change','root_cause','Wrong ingredient ratio',2),
('Taste Change','root_cause','Recipe not followed',3),
('Taste Change','root_cause','Cooking time issue',4),
('Taste Change','root_cause','Retort process affected quality',5),
('Taste Change','root_cause','Storage condition issue',6),
('Taste Change','root_cause','Other',7),
('Product Spoiled','product_handling','Discard Required',1),
('Product Spoiled','product_handling','Hold for Investigation',2),
('Product Spoiled','machine_check','Review retort process',1),
('Product Spoiled','machine_check','Check storage condition',2),
('Product Spoiled','machine_check','Check ingredient quality',3),
('Product Spoiled','machine_check','Investigate contamination source',4),
('Product Spoiled','related_tool','Retort Machine',1),
('Product Spoiled','related_tool','Storage Area',2),
('Product Spoiled','related_tool','Temperature Record',3),
('Product Spoiled','related_tool','Ingredient Record',4),
('Product Spoiled','related_tool','Sealing Machine',5),
('Product Spoiled','root_cause','Retort process insufficient',1),
('Product Spoiled','root_cause','Retort temperature/time issue',2),
('Product Spoiled','root_cause','Storage temperature issue',3),
('Product Spoiled','root_cause','Storage hygiene issue',4),
('Product Spoiled','root_cause','Ingredient contaminated',5),
('Product Spoiled','root_cause','Seal failure',6),
('Product Spoiled','root_cause','Other',7),
('Foreign Matter','product_handling','Discard Required',1),
('Foreign Matter','product_handling','Hold for Investigation',2),
('Foreign Matter','product_handling','To Be Decided After Inspection',3),
('Foreign Matter','machine_check','Inspect preparation area',1),
('Foreign Matter','machine_check','Inspect packing area cleanliness',2),
('Foreign Matter','machine_check','Review worker hygiene / handling process',3),
('Foreign Matter','machine_check','Update cleaning checklist',4),
('Foreign Matter','related_tool','Preparation Table',1),
('Foreign Matter','related_tool','Packing Table',2),
('Foreign Matter','related_tool','Cleaning Checklist',3),
('Foreign Matter','related_tool','PPE',4),
('Foreign Matter','related_tool','Ingredient Inspection Area',5),
('Foreign Matter','related_tool','Packaging Area',6),
('Foreign Matter','root_cause','Foreign object from preparation area',1),
('Foreign Matter','root_cause','Foreign object entered during packing',2),
('Foreign Matter','root_cause','Cleaning not properly done',3),
('Foreign Matter','root_cause','Worker hygiene issue',4),
('Foreign Matter','root_cause','PPE not properly used',5),
('Foreign Matter','root_cause','Packing table cleanliness issue',6),
('Foreign Matter','root_cause','Other',7),
('Weight Issue','product_handling','Rework Required',1),
('Weight Issue','product_handling','Repack Required',2),
('Weight Issue','product_handling','Release After Check',3),
('Weight Issue','product_handling','To Be Decided After Inspection',4),
('Weight Issue','machine_check','Check weighing scale calibration',1),
('Weight Issue','machine_check','Review filling / portioning process',2),
('Weight Issue','machine_check','Review worker weighing procedure',3),
('Weight Issue','machine_check','Check final weight checking process',4),
('Weight Issue','related_tool','Weighing Scale',1),
('Weight Issue','related_tool','Filling Scoop',2),
('Weight Issue','related_tool','Weight Checking Checklist',3),
('Weight Issue','related_tool','Packing Area',4),
('Weight Issue','root_cause','Weighing scale not calibrated',1),
('Weight Issue','root_cause','Scale reading unstable',2),
('Weight Issue','root_cause','Incorrect filling quantity',3),
('Weight Issue','root_cause','Worker weighing procedure not followed',4),
('Weight Issue','root_cause','Product portioning inconsistent',5),
('Weight Issue','root_cause','No final weight check',6),
('Weight Issue','root_cause','Other',7),
('Packaging Material Damaged','product_handling','Repack Required',1),
('Packaging Material Damaged','product_handling','Discard Required',2),
('Packaging Material Damaged','product_handling','Release After Check',3),
('Packaging Material Damaged','product_handling','To Be Decided After Inspection',4),
('Packaging Material Damaged','machine_check','Check packaging material supplier',1),
('Packaging Material Damaged','machine_check','Inspect packaging material storage condition',2),
('Packaging Material Damaged','machine_check','Review packaging handling process',3),
('Packaging Material Damaged','machine_check','Check packaging inspection process',4),
('Packaging Material Damaged','related_tool','Packaging Material',1),
('Packaging Material Damaged','related_tool','Retort Pouch',2),
('Packaging Material Damaged','related_tool','Packaging Storage Area',3),
('Packaging Material Damaged','related_tool','Supplier Batch',4),
('Packaging Material Damaged','related_tool','Packing Area',5),
('Packaging Material Damaged','root_cause','Supplier issue',1),
('Packaging Material Damaged','root_cause','Packaging quality issue',2),
('Packaging Material Damaged','root_cause','Packaging stored incorrectly',3),
('Packaging Material Damaged','root_cause','Packaging damaged before use',4),
('Packaging Material Damaged','root_cause','Packaging handled roughly',5),
('Packaging Material Damaged','root_cause','Packaging inspection not done before use',6),
('Packaging Material Damaged','root_cause','Other',7),
('Retort Process Issue','product_handling','Discard Required',1),
('Retort Process Issue','product_handling','Hold for Investigation',2),
('Retort Process Issue','product_handling','To Be Decided After Inspection',3),
('Retort Process Issue','machine_check','Check retort temperature / pressure',1),
('Retort Process Issue','machine_check','Review retort time setting',2),
('Retort Process Issue','machine_check','Check retort machine record',3),
('Retort Process Issue','machine_check','Review retort SOP',4),
('Retort Process Issue','related_tool','Retort Machine',1),
('Retort Process Issue','related_tool','Retort Record',2),
('Retort Process Issue','related_tool','Temperature Gauge',3),
('Retort Process Issue','related_tool','Pressure Gauge',4),
('Retort Process Issue','related_tool','Retort SOP',5),
('Retort Process Issue','root_cause','Retort time setting incorrect',1),
('Retort Process Issue','root_cause','Retort temperature setting incorrect',2),
('Retort Process Issue','root_cause','Retort pressure issue',3),
('Retort Process Issue','root_cause','Retort process not completed properly',4),
('Retort Process Issue','root_cause','Retort record not checked',5),
('Retort Process Issue','root_cause','Retort SOP not followed',6),
('Retort Process Issue','root_cause','Machine malfunction',7),
('Retort Process Issue','root_cause','Other',8),
('Other','product_handling','To Be Decided After Inspection',1),
('Other','product_handling','Relabel Required',2),
('Other','product_handling','Repack Required',3),
('Other','product_handling','Rework Required',4),
('Other','product_handling','Discard Required',5),
('Other','product_handling','Release After Check',6),
('Other','machine_check','To Be Decided After Investigation',1),
('Other','machine_check','Review process SOP',2),
('Other','machine_check','Check related machine / tool',3),
('Other','machine_check','Check worker handling process',4),
('Other','machine_check','Check material quality',5),
('Other','related_tool','Related Machine / Tool',1),
('Other','related_tool','Process Area',2),
('Other','related_tool','Material',3),
('Other','related_tool','Worker Handling',4),
('Other','related_tool','SOP / Checklist',5),
('Other','root_cause','Need further investigation',1),
('Other','root_cause','Cause not confirmed',2),
('Other','root_cause','Other',3),
('Colour / Texture Change','product_handling','Hold for Investigation',1),
('Colour / Texture Change','product_handling','Discard Required',2),
('Colour / Texture Change','product_handling','Release After Review',3),
('Colour / Texture Change','machine_check','Review cooking process',1),
('Colour / Texture Change','machine_check','Check retort process',2),
('Colour / Texture Change','machine_check','Check storage condition',3),
('Colour / Texture Change','machine_check','Review ingredient quality',4),
('Colour / Texture Change','related_tool','Cooking Equipment',1),
('Colour / Texture Change','related_tool','Cooking Record',2),
('Colour / Texture Change','related_tool','Retort Machine',3),
('Colour / Texture Change','related_tool','Retort Record',4),
('Colour / Texture Change','related_tool','Temperature / Pressure Gauge',5),
('Colour / Texture Change','related_tool','Storage Area',6),
('Colour / Texture Change','root_cause','Cooking time issue',1),
('Colour / Texture Change','root_cause','Cooking temperature issue',2),
('Colour / Texture Change','root_cause','Retort temperature issue',3),
('Colour / Texture Change','root_cause','Retort time issue',4),
('Colour / Texture Change','root_cause','Product over-processed',5),
('Colour / Texture Change','root_cause','Product under-processed',6),
('Colour / Texture Change','root_cause','Ingredient quality issue',7),
('Colour / Texture Change','root_cause','Storage condition issue',8),
('Colour / Texture Change','root_cause','Other',9),
('Ingredient Quality Issue','product_handling','Hold for Investigation',1),
('Ingredient Quality Issue','product_handling','Discard Required',2),
('Ingredient Quality Issue','product_handling','Release After Review',3),
('Ingredient Quality Issue','machine_check','Check ingredient quality',1),
('Ingredient Quality Issue','machine_check','Review supplier batch record',2),
('Ingredient Quality Issue','machine_check','Inspect preparation area',3),
('Ingredient Quality Issue','machine_check','Review worker hygiene process',4),
('Ingredient Quality Issue','related_tool','Ingredient Record',1),
('Ingredient Quality Issue','related_tool','Supplier Batch Record',2),
('Ingredient Quality Issue','related_tool','Preparation Table',3),
('Ingredient Quality Issue','related_tool','Cleaning Checklist',4),
('Ingredient Quality Issue','related_tool','PPE',5),
('Ingredient Quality Issue','root_cause','Ingredient not fresh',1),
('Ingredient Quality Issue','root_cause','Ingredient quality not accepted',2),
('Ingredient Quality Issue','root_cause','Wrong ingredient used',3),
('Ingredient Quality Issue','root_cause','Supplier batch issue',4),
('Ingredient Quality Issue','root_cause','Foreign material from ingredient',5),
('Ingredient Quality Issue','root_cause','Preparation hygiene issue',6),
('Ingredient Quality Issue','root_cause','Other',7),
('Wrong Batch Code on Label','product_handling','Relabel Required',1),
('Wrong Batch Code on Label','product_handling','Hold for Investigation',2),
('Wrong Batch Code on Label','product_handling','Discard Required if cannot be corrected',3),
('Wrong Batch Code on Label','machine_check','Verify batch code on date stamp / printer',1),
('Wrong Batch Code on Label','machine_check','Check batch record before labelling',2),
('Wrong Batch Code on Label','machine_check','Perform test print before production',3),
('Wrong Batch Code on Label','machine_check','Review labelling checklist',4),
('Wrong Batch Code on Label','related_tool','Date Stamp Printer',1),
('Wrong Batch Code on Label','related_tool','Label Printer',2),
('Wrong Batch Code on Label','related_tool','Batch Record',3),
('Wrong Batch Code on Label','related_tool','Labelling Checklist',4),
('Wrong Batch Code on Label','root_cause','Wrong batch code set',1),
('Wrong Batch Code on Label','root_cause','Batch record not checked',2),
('Wrong Batch Code on Label','root_cause','Date stamp / label setup not verified',3),
('Wrong Batch Code on Label','root_cause','Test print not done',4),
('Wrong Batch Code on Label','root_cause','Other',5)
ON CONFLICT (defect_type, option_type, option_value) DO UPDATE SET sort_order = EXCLUDED.sort_order, is_active = TRUE;
